"""End-to-end leak test: synthetic audit must not emit any sentinel value.

This test:
1. Loads ``tests/fixtures/sentinel.txt`` (4 forms of the test privkey).
2. Runs a synthetic audit pipeline that constructs Verdict + uses Secret +
   logs through the redaction pipeline.
3. Captures stdout / stderr / log output.
4. ``grep -F -f sentinel.txt`` over the captured output must return zero matches.

Run as part of CI's "Sentinel leak gate" step. Also runnable standalone:
    uv run pytest tests/security/no_leak_e2e.py -v
"""

from __future__ import annotations

import io
import sys
from pathlib import Path
from unittest.mock import patch

import pytest

from wallet_self_audit.crypto.secret import Secret
from wallet_self_audit.logging.redaction import (
    allowlist_filter,
    fail_closed_guard,
    suspect_hex_scrub,
)
from wallet_self_audit.verdict import VerdictWithoutKey

# Public, documented test privkey — same value as in scripts/generate_sentinel.py.
TEST_PRIVKEY_INT = 0xC0FFEEC0FFEEC0FFEEC0FFEEC0FFEEC0FFEEC0FFEEC0FFEEC0FFEEC0FFEEDEAD
TEST_PRIVKEY_HEX = f"{TEST_PRIVKEY_INT:064x}"


_SENTINEL_PATH = Path(__file__).resolve().parent.parent / "fixtures" / "sentinel.txt"


@pytest.mark.security
def test_sentinel_file_exists() -> None:
    """Sentinel file must be generated by ``scripts/generate_sentinel.py``."""
    if not _SENTINEL_PATH.exists():
        pytest.skip(f"sentinel not generated yet: {_SENTINEL_PATH}")
    assert _SENTINEL_PATH.stat().st_size > 0


@pytest.mark.security
def test_synthetic_audit_does_not_leak_sentinel() -> None:
    """E2E: synthetic audit output must NOT contain any sentinel form."""
    if not _SENTINEL_PATH.exists():
        pytest.skip("sentinel not generated yet")

    sentinel_lines = [
        ln.strip() for ln in _SENTINEL_PATH.read_text(encoding="utf-8").splitlines() if ln.strip()
    ]

    captured_stdout = io.StringIO()
    captured_stderr = io.StringIO()

    with patch("sys.stdout", captured_stdout), patch("sys.stderr", captured_stderr):
        # 1. Load privkey into Secret, exercise redaction.
        with Secret(32) as s:
            s.view()[:] = bytes.fromhex(TEST_PRIVKEY_HEX)
            # repr of Secret must not include bytes.
            print(repr(s), file=sys.stdout)

        # 2. Construct a VULNERABLE verdict (with a fingerprint, NOT the privkey).
        verdict = VerdictWithoutKey(
            address="bc1qexample",
            status="VULNERABLE",
            finding="r_collision",
            confidence=0.99,
            key_fingerprint="0123456789abcdef",  # this is fine — it's 16 chars
            recommendation="Move funds to a fresh wallet now.",
            evidence_refs=("a" * 64,),  # legit txid
            audit_id="11111111-2222-3333-4444-555555555555",
            checks_performed=("r_collision",),
        )

        # 3. Print verdict via to_public_json.
        import json

        print(json.dumps(verdict.to_public_json()), file=sys.stdout)

        # 4. Run all redaction processors with a malicious event_dict
        #    containing the privkey — must be dropped/scrubbed/raise.
        try:
            event = {"privkey": TEST_PRIVKEY_HEX, "event": "malicious"}
            after_allow = allowlist_filter(None, "info", event)
            after_scrub = suspect_hex_scrub(None, "info", after_allow)
            fail_closed_guard(None, "info", after_scrub)
            print(json.dumps(after_scrub), file=sys.stdout)
        except Exception as exc:
            # Expected — fail_closed_guard may raise. The exception message
            # itself must not contain the privkey.
            print(f"redaction raised: {type(exc).__name__}", file=sys.stderr)

    full_output = captured_stdout.getvalue() + "\n" + captured_stderr.getvalue()

    leaks: list[str] = []
    for sentinel_value in sentinel_lines:
        if sentinel_value in full_output:
            leaks.append(sentinel_value)

    assert not leaks, (
        f"Sentinel leak detected — {len(leaks)} value(s) found in audit output. "
        f"This is a P0 security failure. First leak: {leaks[0][:16]}..."
    )


if __name__ == "__main__":  # pragma: no cover
    # Allow running directly as a script for CI's leak gate.
    sys.exit(pytest.main([__file__, "-v"]))
