"""Milk Sad detector — CVE-2023-39910.

Background: ``libbitcoin-explorer`` (``bx seed``) used ``std::mt19937`` seeded
from a 32-bit Unix timestamp via ``std::seed_seq``. Four ``operator()`` calls
gave four ``uint32_t`` values, big-endian-packed into 16 bytes of "entropy",
which fed BIP-39 to produce a 12-word mnemonic. The keyspace is therefore
2^32 timestamps — fully enumerable in seconds.

This detector enumerates timestamps in a window and flags a wallet as
``VULNERABLE`` if a match is found.

Two scan modes:
- **Entropy direct compare** (``scan_window``): the user has the mnemonic
  → we have its entropy → we just compare 16 bytes per candidate. No
  PBKDF2, no BIP-32. ~50M timestamps/sec/core upper bound.
- **Address compare** (``scan_window_by_addresses``): the user has only an
  address. We must run BIP-32 derivation per candidate, which is dominated
  by PBKDF2 (~250 ops/sec/core). Slow but the only option without secrets.

Both modes use ``multiprocessing`` to parallelise across P-cores.

The implementation is **stage-validated**: ``check_fixtures()`` (in
mt19937_cpp) must succeed before any scan starts. If the validation fixture
ever fails, ``MilkSadValidationFailed`` is raised — better to crash than
to scan with a wrong oracle and emit a false ``SAFE``.

NOTE on stdlib variants: ``mt19937_cpp.py`` is byte-identical with libc++
on macOS arm64. ``bx seed`` was historically built primarily on Linux with
libstdc++, which uses XOR (not addition) in seed_seq phase 2. Production
deployments should run ``check_fixtures_libstdcxx()`` against fixtures
generated by gcc on Linux. Phase 8 will ship those.
"""

from __future__ import annotations

import multiprocessing as mp
from collections.abc import Iterator
from dataclasses import dataclass
from typing import Final

from wallet_self_audit.prng.derive import first_addresses
from wallet_self_audit.prng.mt19937_cpp import (
    check_fixtures,
    entropy_from_timestamp,
)

# Default Milk Sad window: 2017-01-01 (libbitcoin-explorer 3.x first release
# era) → 2023-08-15 (CVE patch). Anyone could have used bx seed in that
# window. Override via CLI for a narrower / wider scan.
MILK_SAD_WINDOW_DEFAULT_START: Final[int] = 1483228800  # 2017-01-01 UTC
MILK_SAD_WINDOW_DEFAULT_END: Final[int] = 1692057600  # 2023-08-15 UTC


class MilkSadValidationFailed(RuntimeError):
    """Raised if the in-tree mt19937 fixture fails to validate.

    A failed validation means we cannot trust the mt19937 reproduction —
    a Milk Sad scan would produce false negatives (wrongly tell users
    their wallet is SAFE). Refuse to run.
    """


@dataclass(frozen=True, slots=True)
class MilkSadHit:
    """A single match between user's entropy/address and a timestamp candidate."""

    timestamp: int
    candidate_entropy_hex: str
    matched_via: str  # "entropy" | "p2pkh_bip44" | "p2sh_p2wpkh_bip49" | "p2wpkh_bip84"


def _ensure_validated() -> None:
    """Refuse to run if the mt19937 fixture validation fails."""
    if not check_fixtures():
        raise MilkSadValidationFailed(
            "mt19937 fixtures missing or failed validation; refusing to "
            "Milk Sad scan with an unvalidated oracle (would produce false negatives)"
        )


# ---------------------------------------------------------------------------
# Mode 1: entropy-direct comparison (fast — no BIP-32)
# ---------------------------------------------------------------------------
def _scan_entropy_chunk(args: tuple[int, int, bytes]) -> MilkSadHit | None:
    """Worker: scan ``[start, end)`` and return the first matching hit.

    Args:
        args: (start_inclusive, end_exclusive, target_entropy_bytes).
    """
    start, end, target = args
    n_words = len(target) * 8 // 11 + 1  # rough — adjusted below
    # Map entropy length to BIP-39 word count.
    bits = len(target) * 8
    cs = bits // 32
    n_words = (bits + cs) // 11
    for ts in range(start, end):
        cand = entropy_from_timestamp(ts, n_words=n_words)
        if cand == target:
            return MilkSadHit(
                timestamp=ts,
                candidate_entropy_hex=cand.hex(),
                matched_via="entropy",
            )
    return None


def scan_window(
    target_entropy: bytes,
    start: int = MILK_SAD_WINDOW_DEFAULT_START,
    end: int = MILK_SAD_WINDOW_DEFAULT_END,
    n_workers: int | None = None,
) -> MilkSadHit | None:
    """Scan ``[start, end)`` for a timestamp whose mt19937 entropy matches.

    Args:
        target_entropy: User's BIP-39 entropy (16, 20, 24, 28, or 32 bytes).
        start: Inclusive Unix timestamp (default 2017-01-01).
        end: Exclusive Unix timestamp (default 2023-08-15).
        n_workers: Number of multiprocessing workers (default = P-cores).

    Returns:
        ``MilkSadHit`` on match, or ``None`` if the window is clean.

    Raises:
        MilkSadValidationFailed: If mt19937 fixture validation fails.
        ValueError: If ``target_entropy`` length is unsupported.
    """
    _ensure_validated()
    if len(target_entropy) not in (16, 20, 24, 28, 32):
        raise ValueError(f"unsupported entropy length {len(target_entropy)}")
    if end <= start:
        return None

    workers = n_workers or _default_workers()
    chunks = list(_chunk_window(start, end, workers))

    args_list = [(c0, c1, target_entropy) for (c0, c1) in chunks]
    if workers == 1:
        for args in args_list:
            hit = _scan_entropy_chunk(args)
            if hit is not None:
                return hit
        return None

    with mp.get_context("spawn").Pool(processes=workers) as pool:
        for hit in pool.imap_unordered(_scan_entropy_chunk, args_list):
            if hit is not None:
                pool.terminate()
                return hit
    return None


# ---------------------------------------------------------------------------
# Mode 2: address comparison (slower — full BIP-32 per candidate)
# ---------------------------------------------------------------------------
def _scan_addresses_chunk(args: tuple[int, int, frozenset[str]]) -> MilkSadHit | None:
    """Worker: derive candidate addresses, compare against ``targets``."""
    start, end, targets = args
    for ts in range(start, end):
        cand = entropy_from_timestamp(ts, n_words=12)
        addrs = first_addresses(cand)
        for kind, addr in (
            ("p2pkh_bip44", addrs.p2pkh_bip44),
            ("p2sh_p2wpkh_bip49", addrs.p2sh_p2wpkh_bip49),
            ("p2wpkh_bip84", addrs.p2wpkh_bip84),
        ):
            if addr is not None and addr in targets:
                return MilkSadHit(
                    timestamp=ts,
                    candidate_entropy_hex=cand.hex(),
                    matched_via=kind,
                )
    return None


def scan_window_by_addresses(
    target_addresses: frozenset[str],
    start: int = MILK_SAD_WINDOW_DEFAULT_START,
    end: int = MILK_SAD_WINDOW_DEFAULT_END,
    n_workers: int | None = None,
) -> MilkSadHit | None:
    """Scan ``[start, end)`` and compare derived addresses against a set.

    Slower than ``scan_window`` (PBKDF2 dominates: ~250 cands/sec/core)
    but doesn't require the user's mnemonic.

    Args:
        target_addresses: Set of one or more known receive addresses for
            the wallet (any of ``1...``, ``3...``, ``bc1q...``).
        start: Inclusive Unix timestamp.
        end: Exclusive Unix timestamp.
        n_workers: Multiprocessing workers (default = P-cores).
    """
    _ensure_validated()
    if not target_addresses:
        raise ValueError("target_addresses must be non-empty")

    workers = n_workers or _default_workers()
    chunks = list(_chunk_window(start, end, workers))
    args_list = [(c0, c1, target_addresses) for (c0, c1) in chunks]
    if workers == 1:
        for args in args_list:
            hit = _scan_addresses_chunk(args)
            if hit is not None:
                return hit
        return None

    with mp.get_context("spawn").Pool(processes=workers) as pool:
        for hit in pool.imap_unordered(_scan_addresses_chunk, args_list):
            if hit is not None:
                pool.terminate()
                return hit
    return None


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _default_workers() -> int:
    """Conservative default — leave one core for OS / orchestrator."""
    cpus = mp.cpu_count() or 2
    return max(1, cpus - 1)


def _chunk_window(start: int, end: int, n: int) -> Iterator[tuple[int, int]]:
    """Split ``[start, end)`` into ``n`` roughly-equal contiguous chunks."""
    if n <= 0:
        raise ValueError("n must be positive")
    span = end - start
    size = max(1, span // n)
    cur = start
    for i in range(n):
        nxt = end if i == n - 1 else min(end, cur + size)
        if nxt > cur:
            yield (cur, nxt)
        cur = nxt


__all__ = [
    "MILK_SAD_WINDOW_DEFAULT_END",
    "MILK_SAD_WINDOW_DEFAULT_START",
    "MilkSadHit",
    "MilkSadValidationFailed",
    "scan_window",
    "scan_window_by_addresses",
]
