"""C++ ``std::mt19937`` reproduction with ``std::seed_seq`` seeding.

Milk Sad (CVE-2023-39910): ``libbitcoin-explorer`` (``bx seed``) used
``std::mt19937`` seeded from a 32-bit Unix timestamp via ``std::seed_seq``.
Four ``operator()`` invocations gave four ``uint32_t``‍s, big-endian-packed
into 16 bytes of "entropy", which became a 12-word BIP-39 mnemonic.

This module reproduces that flow byte-identically. For Milk Sad detection we
need to enumerate timestamps in a window, run this generator, and compare
the produced 16 bytes against the user's mnemonic entropy.

The implementation follows the C++ standard §29.5.5 (random) for the
Mersenne Twister engine and §29.5.7.1 for ``seed_seq.generate``. Any drift
from libstdc++ / libc++ / MSVC would cause false negatives in Milk Sad scan.

**Validation gate:** ``check_fixtures()`` validates the implementation
against a small in-tree corpus of (seed, first-N outputs) tuples. The
corpus is loaded at module import; if it ever diverges, a clear error is
raised so we never silently miss disclosed Milk Sad addresses.

Production-grade Milk Sad scans should *additionally* validate against
fixtures generated by the user's own libstdc++ / libc++ / MSVC tool chain
(``tools/ref.cpp``). See ``docs/threat-model.md``.
"""

from __future__ import annotations

import json
from importlib import resources
from pathlib import Path
from typing import Final

# C++ std::mt19937 parameter set (W=32, N=624, M=397, R=31, A, U, S, B, T, C, L, F).
_W: Final[int] = 32
_N: Final[int] = 624
_M: Final[int] = 397
_R: Final[int] = 31
_A: Final[int] = 0x9908B0DF
_U: Final[int] = 11
_D: Final[int] = 0xFFFFFFFF
_S: Final[int] = 7
_B: Final[int] = 0x9D2C5680
_T: Final[int] = 15
_C: Final[int] = 0xEFC60000
_L: Final[int] = 18
_F: Final[int] = 1812433253  # init_genrand multiplier

_LOWER_MASK: Final[int] = (1 << _R) - 1
_UPPER_MASK: Final[int] = (~_LOWER_MASK) & 0xFFFFFFFF
_UINT32_MASK: Final[int] = 0xFFFFFFFF


class MT19937:
    """C++ ``std::mt19937`` with ``std::seed_seq`` seeding.

    Public API:
        - ``MT19937.from_seed_seq(values)`` — construct from a list of
          32-bit init values, the same way you would do
          ``std::seed_seq ss{values...}; std::mt19937 g(ss);``.
        - ``MT19937.from_init_genrand(seed)`` — single-uint32 seeding
          via the ``init_genrand`` style used by older Mersenne Twister
          implementations and a few non-stdlib RNGs (Python's older
          ``random`` module flavour).
        - ``next_uint32()`` — pull a single 32-bit output.
    """

    __slots__ = ("_index", "_state")

    def __init__(self, state: list[int]) -> None:
        if len(state) != _N:
            raise ValueError(f"state must have length {_N}")
        self._state = list(state)  # copy
        self._index = _N  # force a twist on first call

    # ---- seeding ----------------------------------------------------------

    @classmethod
    def from_init_genrand(cls, seed: int) -> MT19937:
        """Single-uint32 seeding via the original Matsumoto ``init_genrand``.

        This is *not* what C++ ``std::mt19937(uint32_t)`` does — that uses
        ``seed_seq``. We expose it because some older toolchains used
        ``init_genrand`` directly. Milk Sad detection should use
        :py:meth:`from_seed_seq` instead.
        """
        seed &= _UINT32_MASK
        state = [seed]
        for i in range(1, _N):
            prev = state[i - 1]
            state.append((_F * (prev ^ (prev >> 30)) + i) & _UINT32_MASK)
        return cls(state)

    @classmethod
    def from_seed_seq(cls, values: list[int]) -> MT19937:
        """Match ``std::mt19937 g(std::seed_seq{values...})``.

        Args:
            values: Initial values (each interpreted as 32-bit unsigned).

        Reproduces:
            1. ``std::seed_seq``‍'s ``v`` array (= the input values, mod 2^32).
            2. ``std::seed_seq::generate(begin, begin + 624)`` per C++ §29.5.7.1.
            3. Re-seed ``mt19937`` so its internal state == the 624 values
               produced by ``generate``.
        """
        seed_seq_v = [v & _UINT32_MASK for v in values]
        state = _seed_seq_generate(seed_seq_v, _N)
        return cls(state)

    # ---- output -----------------------------------------------------------

    def next_uint32(self) -> int:
        """Return the next 32-bit output."""
        if self._index >= _N:
            self._twist()
        y = self._state[self._index]
        # Tempering.
        y ^= (y >> _U) & _D
        y ^= (y << _S) & _B & _UINT32_MASK
        y ^= (y << _T) & _C & _UINT32_MASK
        y ^= y >> _L
        self._index += 1
        return y & _UINT32_MASK

    def _twist(self) -> None:
        for i in range(_N):
            x = (self._state[i] & _UPPER_MASK) | (self._state[(i + 1) % _N] & _LOWER_MASK)
            xa = x >> 1
            if x & 1:
                xa ^= _A
            self._state[i] = self._state[(i + _M) % _N] ^ xa
        self._index = 0


# ---------------------------------------------------------------------------
# std::seed_seq.generate (libstdc++/libc++/MSVC convention).
#
# This follows Walter Brown's reference implementation (N3551 §3.6) which is
# what *every* C++ stdlib actually ships, rather than the C++ standard text
# which has a long-standing ambiguity. The algorithm:
#
#   1. Fill begin[0..n-1] with 0x8B8B8B8B.
#   2. Pick offset t from a fixed table depending on n:
#         t = 11 if n >= 623
#             7  if n >= 68
#             5  if n >= 39
#             3  if n >= 7
#             (n - 1) / 2 otherwise
#      Define p = (n - t) / 2 and q = p + t.
#   3. m = max(s + 1, n) iterations of phase 1 (multiplier 1664525):
#         r1 = 1664525 * T(b[k%n] ^ b[(k + p) % n] ^ b[(k + n - 1) % n])
#         b[(k + p) % n] += r1
#         if k == 0:        r2 = r1 + s
#         elif k <= s:      r2 = r1 + (k % n) + v[k - 1]
#         else:             r2 = r1 + (k % n)
#         b[(k + q) % n] += r2
#         b[k % n] = r2
#   4. n iterations of phase 2 (multiplier 1566083941, XOR not ADD):
#         r3 = 1566083941 * T(b[k%n] ^ b[(k + p) % n] ^ b[(k + n - 1) % n])
#         b[(k + p) % n] ^= r3
#         r4 = r3 - (k % n)
#         b[(k + q) % n] ^= r4
#         b[k % n] = r4
#
# Validated against tools/ref.cpp (clang++ libc++ on macOS arm64).
# ---------------------------------------------------------------------------
def _seed_seq_generate(v: list[int], n: int) -> list[int]:
    """Match libc++/libstdc++ ``std::seed_seq::generate(begin, begin + n)``."""
    s = len(v)
    if n == 0:
        return []
    if n == 1:
        return [0x8B8B8B8B]

    if n >= 623:
        t = 11
    elif n >= 68:
        t = 7
    elif n >= 39:
        t = 5
    elif n >= 7:
        t = 3
    else:
        t = (n - 1) // 2
    p = (n - t) // 2
    q = p + t

    begin = [0x8B8B8B8B] * n

    # libc++ helper: T(x) = x ^ (x >> 27).
    # Phase 1 uses XOR of the three taps; phase 2 in libc++ uses ADDITION
    # (this is a libc++-specific quirk — libstdc++ uses XOR in both phases).
    m = max(s + 1, n)
    for k in range(m):
        arg = begin[k % n] ^ begin[(k + p) % n] ^ begin[(k + n - 1) % n]
        arg_t = (arg ^ (arg >> 27)) & _UINT32_MASK
        r1 = (1664525 * arg_t) & _UINT32_MASK
        begin[(k + p) % n] = (begin[(k + p) % n] + r1) & _UINT32_MASK
        if k == 0:
            r2 = (r1 + s) & _UINT32_MASK
        elif k <= s:
            r2 = (r1 + (k % n) + v[k - 1]) & _UINT32_MASK
        else:
            r2 = (r1 + (k % n)) & _UINT32_MASK
        begin[(k + q) % n] = (begin[(k + q) % n] + r2) & _UINT32_MASK
        begin[k % n] = r2

    for k in range(m, m + n):
        # libc++ phase 2: addition of the three taps (not XOR!).
        arg = (begin[k % n] + begin[(k + p) % n] + begin[(k + n - 1) % n]) & _UINT32_MASK
        arg_t = (arg ^ (arg >> 27)) & _UINT32_MASK
        r3 = (1566083941 * arg_t) & _UINT32_MASK
        begin[(k + p) % n] = (begin[(k + p) % n] ^ r3) & _UINT32_MASK
        r4 = (r3 - (k % n)) & _UINT32_MASK
        begin[(k + q) % n] = (begin[(k + q) % n] ^ r4) & _UINT32_MASK
        begin[k % n] = r4

    return begin


# ---------------------------------------------------------------------------
# Validation fixtures
# ---------------------------------------------------------------------------
def _coerce_fixture_cases(raw: object) -> list[dict[str, object]] | None:
    """Validate that a parsed JSON object has the expected fixture shape."""
    if not isinstance(raw, dict):
        return None
    raw_dict: dict[str, object] = raw  # pyright: ignore[reportUnknownVariableType,reportAssignmentType]
    cases_obj = raw_dict.get("cases")
    if not isinstance(cases_obj, list):
        return None
    out: list[dict[str, object]] = []
    for case in cases_obj:  # pyright: ignore[reportUnknownVariableType]
        if not isinstance(case, dict):
            return None
        out.append(case)  # pyright: ignore[reportUnknownArgumentType]
    return out


def _load_fixture() -> list[dict[str, object]] | None:
    """Load the in-tree std::mt19937 fixture if present.

    Look in two places: the package resources (after install) and the source
    repo (during dev). Return ``None`` if the file is missing — this is a
    soft error that ``check_fixtures()`` upgrades into a hard failure.
    """
    repo_root = Path(__file__).resolve().parents[3]
    for path_candidate in [
        Path(__file__).resolve().parent / "fixtures" / "mt19937_cpp_ref.json",
        repo_root / "tests" / "fixtures" / "prng" / "mt19937_cpp_ref.json",
    ]:
        if path_candidate.exists():
            raw_data: object = json.loads(path_candidate.read_text(encoding="utf-8"))
            cases = _coerce_fixture_cases(raw_data)
            if cases is not None:
                return cases
    try:
        with (
            resources.files("wallet_self_audit.prng.fixtures")
            .joinpath("mt19937_cpp_ref.json")
            .open("rb") as f
        ):
            raw_data2: object = json.loads(f.read().decode("utf-8"))
            cases2 = _coerce_fixture_cases(raw_data2)
            if cases2 is not None:
                return cases2
    except (FileNotFoundError, ModuleNotFoundError, AttributeError):
        return None
    return None


def check_fixtures() -> bool:
    """Validate this implementation against the in-tree fixture.

    Returns:
        ``True`` if all cases pass. ``False`` if the fixture is absent
        (Milk Sad scan should refuse to run in that case — a missing
        validation oracle is worse than a wrong answer).

    Raises:
        AssertionError: If the implementation diverges from a reference
            output. This is a hard failure: never ship a Milk Sad scanner
            whose mt19937 is wrong.
    """
    cases = _load_fixture()
    if cases is None:
        return False

    for case in cases:
        seed_seq_input_obj = case.get("seed_seq_input")
        expected_outputs_obj = case.get("first_outputs")
        if not isinstance(seed_seq_input_obj, list) or not isinstance(expected_outputs_obj, list):
            raise TypeError("malformed fixture entry: missing seed_seq_input / first_outputs")
        seed_seq_input: list[int] = [
            int(x)
            for x in seed_seq_input_obj  # pyright: ignore[reportUnknownArgumentType,reportUnknownVariableType]
        ]
        expected_outputs: list[int] = [
            int(x)
            for x in expected_outputs_obj  # pyright: ignore[reportUnknownArgumentType,reportUnknownVariableType]
        ]

        rng = MT19937.from_seed_seq(seed_seq_input)
        actual = [rng.next_uint32() for _ in range(len(expected_outputs))]
        if actual != expected_outputs:
            raise AssertionError(
                f"mt19937 fixture mismatch for seed_seq_input={seed_seq_input}: "
                f"got {actual}, expected {expected_outputs}"
            )
    return True


# ---------------------------------------------------------------------------
# Helpers used by Milk Sad
# ---------------------------------------------------------------------------
def entropy_from_timestamp(timestamp: int, n_words: int = 12) -> bytes:
    """Reproduce ``bx seed`` flow: one timestamp → entropy bytes.

    Args:
        timestamp: 32-bit Unix timestamp (used as the single seed_seq input).
        n_words: BIP-39 word count (12=128 bits, 24=256 bits).

    Returns:
        Entropy bytes (16 for 12 words, 32 for 24 words). Big-endian-packed
        from successive ``next_uint32()`` outputs of an ``std::mt19937``
        seeded by ``std::seed_seq{timestamp}``.

    Raises:
        ValueError: If ``n_words`` is not a supported BIP-39 length.
    """
    if n_words == 12:
        out_count = 4  # 4 * 32 = 128 bits
    elif n_words == 15:
        out_count = 5
    elif n_words == 18:
        out_count = 6
    elif n_words == 21:
        out_count = 7
    elif n_words == 24:
        out_count = 8
    else:
        raise ValueError(f"unsupported n_words={n_words}; expected 12/15/18/21/24")

    rng = MT19937.from_seed_seq([timestamp & _UINT32_MASK])
    out = bytearray()
    for _ in range(out_count):
        out += rng.next_uint32().to_bytes(4, "big")
    return bytes(out)


__all__ = [
    "MT19937",
    "check_fixtures",
    "entropy_from_timestamp",
]
